In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Reading the ILPD dataset

In [2]:
df = pd.read_csv("ILPD.csv")
df

     Age  Gender    TB   DB   AP  SGPT  SGOT   TP  ALB   A/G  Target
0     65  Female   0.7  0.1  187    16    18  6.8  3.3  0.90       1
1     62    Male  10.9  5.5  699    64   100  7.5  3.2  0.74       1
2     62    Male   7.3  4.1  490    60    68  7.0  3.3  0.89       1
3     58    Male   1.0  0.4  182    14    20  6.8  3.4  1.00       1
4     72    Male   3.9  2.0  195    27    59  7.3  2.4  0.40       1
..   ...     ...   ...  ...  ...   ...   ...  ...  ...   ...     ...
578   60    Male   0.5  0.1  500    20    34  5.9  1.6  0.37       2
579   40    Male   0.6  0.1   98    35    31  6.0  3.2  1.10       1
580   52    Male   0.8  0.2  245    48    49  6.4  3.2  1.00       1
581   31    Male   1.3  0.5  184    29    32  6.8  3.4  1.00       1
582   38    Male   1.0  0.3  216    21    24  7.3  4.4  1.50       2

[583 rows x 11 columns]

# Encoding Gender column

In [3]:
from sklearn.preprocessing import LabelEncoder

label_encoder_x = LabelEncoder()
df['Gender'] = label_encoder_x.fit_transform(df[['Gender']])
df

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

     Age  Gender    TB   DB   AP  SGPT  SGOT   TP  ALB   A/G  Target
0     65       0   0.7  0.1  187    16    18  6.8  3.3  0.90       1
1     62       1  10.9  5.5  699    64   100  7.5  3.2  0.74       1
2     62       1   7.3  4.1  490    60    68  7.0  3.3  0.89       1
3     58       1   1.0  0.4  182    14    20  6.8  3.4  1.00       1
4     72       1   3.9  2.0  195    27    59  7.3  2.4  0.40       1
..   ...     ...   ...  ...  ...   ...   ...  ...  ...   ...     ...
578   60       1   0.5  0.1  500    20    34  5.9  1.6  0.37       2
579   40       1   0.6  0.1   98    35    31  6.0  3.2  1.10       1
580   52       1   0.8  0.2  245    48    49  6.4  3.2  1.00       1
581   31       1   1.3  0.5  184    29    32  6.8  3.4  1.00       1
582   38       1   1.0  0.3  216    21    24  7.3  4.4  1.50       2

[583 rows x 11 columns]

# Checking for NULL values

In [4]:
df.isnull().values.any()

True

In [5]:
df.isnull().sum().sum()

4

In [6]:
df[df.isnull().any(axis=1)]

     Age  Gender   TB   DB   AP  SGPT  SGOT   TP  ALB  A/G  Target
209   45       0  0.9  0.3  189    23    33  6.6  3.9  NaN       1
241   51       1  0.8  0.2  230    24    46  6.5  3.1  NaN       1
253   35       0  0.6  0.2  180    12    15  5.2  2.7  NaN       2
312   27       1  1.3  0.6  106    25    54  8.5  4.8  NaN       2

# Handling Missing data by MultiVariate Imputation

In [7]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.model_selection import train_test_split

df2 = df.copy()

In [8]:
cont_feats = [col for col in df2.columns if df2[col].dtype != object]

In [9]:
iter_imputer = IterativeImputer(random_state=42)
iter_imputed = iter_imputer.fit_transform(df2[cont_feats])
df2 = pd.DataFrame(iter_imputed, columns=cont_feats)

In [10]:
df2['A/G'] = np.round(df2[['A/G']],2)

In [11]:
df2.iloc[[209,241,253,312],:]

      Age  Gender   TB   DB     AP  SGPT  SGOT   TP  ALB   A/G  Target
209  45.0     0.0  0.9  0.3  189.0  23.0  33.0  6.6  3.9  1.31     1.0
241  51.0     1.0  0.8  0.2  230.0  24.0  46.0  6.5  3.1  0.92     1.0
253  35.0     0.0  0.6  0.2  180.0  12.0  15.0  5.2  2.7  0.99     2.0
312  27.0     1.0  1.3  0.6  106.0  25.0  54.0  8.5  4.8  1.37     2.0

In [12]:
df = df2
df

      Age  Gender    TB   DB     AP  SGPT   SGOT   TP  ALB   A/G  Target
0    65.0     0.0   0.7  0.1  187.0  16.0   18.0  6.8  3.3  0.90     1.0
1    62.0     1.0  10.9  5.5  699.0  64.0  100.0  7.5  3.2  0.74     1.0
2    62.0     1.0   7.3  4.1  490.0  60.0   68.0  7.0  3.3  0.89     1.0
3    58.0     1.0   1.0  0.4  182.0  14.0   20.0  6.8  3.4  1.00     1.0
4    72.0     1.0   3.9  2.0  195.0  27.0   59.0  7.3  2.4  0.40     1.0
..    ...     ...   ...  ...    ...   ...    ...  ...  ...   ...     ...
578  60.0     1.0   0.5  0.1  500.0  20.0   34.0  5.9  1.6  0.37     2.0
579  40.0     1.0   0.6  0.1   98.0  35.0   31.0  6.0  3.2  1.10     1.0
580  52.0     1.0   0.8  0.2  245.0  48.0   49.0  6.4  3.2  1.00     1.0
581  31.0     1.0   1.3  0.5  184.0  29.0   32.0  6.8  3.4  1.00     1.0
582  38.0     1.0   1.0  0.3  216.0  21.0   24.0  7.3  4.4  1.50     2.0

[583 rows x 11 columns]

# Log1 p Transformation

In [13]:
# save skewed features
skewed_cols = ['A/G', 'TB', 'AP', 'SGPT']

In [14]:
# Apply log1p transformation on dataframe - just selected values
for c in skewed_cols:
    df[c] = df[c].apply('log1p')

In [15]:
df

,Age,Gender,TB,DB,AP,SGPT,SGOT,TP,ALB,A/G,Target
0,65.0,0.0,0.530628,0.1,5.236442,2.833213,18.0,6.8,3.3,0.641854,1.0
1,62.0,1.0,2.476538,5.5,6.551080,4.174387,100.0,7.5,3.2,0.553885,1.0
2,62.0,1.0,2.116256,4.1,6.196444,4.110874,68.0,7.0,3.3,0.636577,1.0
3,58.0,1.0,0.693147,0.4,5.209486,2.708050,20.0,6.8,3.4,0.693147,1.0
4,72.0,1.0,1.589235,2.0,5.278115,3.332205,59.0,7.3,2.4,0.336472,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,1.0,0.405465,0.1,6.216606,3.044522,34.0,5.9,1.6,0.314811,2.0
579,40.0,1.0,0.470004,0.1,4.595120,3.583519,31.0,6.0,3.2,0.741937,1.0
580,52.0,1.0,0.587787,0.2,5.505332,3.891820,49.0,6.4,3.2,0.693147,1.0
581,31.0,1.0,0.832909,0.5,5.220356,3.401197,32.0,6.8,3.4,0.693147,1.0
582,38.0,1.0,0.693147,0.3,5.379897,3.091042,24.0,7.3,4.4,0.916291,2.0

# Balance Dataset

In [16]:
from sklearn.utils import resample
df.Target.value_counts()

1.0    416
2.0    167
Name: Target, dtype: int64

In [17]:
# Split data on majority and minority.. minority is dataset == 2
minority = df[df.Target == 2]
majority = df[df.Target == 1]

print('Minority size:', minority.shape)
print('Majority size:', majority.shape)

Minority size: (167, 11)
Majority size: (416, 11)

In [18]:
# choosing upsample as even now we do not have too much data
minority_upsample = resample(
    minority, replace=True, n_samples=majority.shape[0])
print('Minority upsampled size:',  minority_upsample.shape)

Minority upsampled size: (416, 11)

In [19]:
# merge majority with upsampled minority
pd.concat([minority_upsample, majority], axis=0)

,Age,Gender,TB,DB,AP,SGPT,SGOT,TP,ALB,A/G,Target
540,42.0,1.0,0.587787,0.2,4.744932,3.091042,23.0,7.0,3.0,0.530628,2.0
218,6.0,1.0,0.470004,0.1,5.669881,3.663562,30.0,4.8,2.0,0.530628,2.0
153,52.0,1.0,0.470004,0.1,5.187386,3.295837,27.0,6.5,3.6,0.788457,2.0
287,43.0,1.0,0.832909,0.6,5.049856,2.772589,20.0,8.0,4.0,0.693147,2.0
539,65.0,0.0,0.530628,0.2,6.008813,3.218876,45.0,7.2,3.5,0.641854,2.0
...,...,...,...,...,...,...,...,...,...,...,...
576,32.0,1.0,2.772589,8.2,5.669881,4.077537,80.0,5.3,2.2,0.530628,1.0
577,32.0,1.0,2.617396,8.4,5.252273,3.367296,47.0,5.4,2.6,0.641854,1.0
579,40.0,1.0,0.470004,0.1,4.595120,3.583519,31.0,6.0,3.2,0.741937,1.0
580,52.0,1.0,0.587787,0.2,5.505332,3.891820,49.0,6.4,3.2,0.693147,1.0
581,31.0,1.0,0.832909,0.5,5.220356,3.401197,32.0,6.8,3.4,0.693147,1.0

In [20]:
# merge majority with upsampled minority
df = pd.concat([minority_upsample, majority], axis=0)
df = df.reset_index(drop=True)
df

,Age,Gender,TB,DB,AP,SGPT,SGOT,TP,ALB,A/G,Target
0,42.0,1.0,0.587787,0.2,4.744932,3.091042,23.0,7.0,3.0,0.530628,2.0
1,6.0,1.0,0.470004,0.1,5.669881,3.663562,30.0,4.8,2.0,0.530628,2.0
2,52.0,1.0,0.470004,0.1,5.187386,3.295837,27.0,6.5,3.6,0.788457,2.0
3,43.0,1.0,0.832909,0.6,5.049856,2.772589,20.0,8.0,4.0,0.693147,2.0
4,65.0,0.0,0.530628,0.2,6.008813,3.218876,45.0,7.2,3.5,0.641854,2.0
...,...,...,...,...,...,...,...,...,...,...,...
827,32.0,1.0,2.772589,8.2,5.669881,4.077537,80.0,5.3,2.2,0.530628,1.0
828,32.0,1.0,2.617396,8.4,5.252273,3.367296,47.0,5.4,2.6,0.641854,1.0
829,40.0,1.0,0.470004,0.1,4.595120,3.583519,31.0,6.0,3.2,0.741937,1.0
830,52.0,1.0,0.587787,0.2,5.505332,3.891820,49.0,6.4,3.2,0.693147,1.0
831,31.0,1.0,0.832909,0.5,5.220356,3.401197,32.0,6.8,3.4,0.693147,1.0

# Splitting into train and test set

In [21]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=123)

In [23]:
from sklearn import preprocessing

standard_scaler = preprocessing.StandardScaler()
standard_data = pd.DataFrame(standard_scaler.fit_transform(X), columns=X.columns)
standardized_X_train = pd.DataFrame(standard_scaler.fit_transform(X_train), columns=X.columns)
standardized_X_test = pd.DataFrame(standard_scaler.fit_transform(X_test), columns=X.columns)

min_max_scaler = preprocessing.MinMaxScaler()
minmax_data = pd.DataFrame(min_max_scaler.fit_transform(X), columns=X.columns)
minmax_X_train = pd.DataFrame(min_max_scaler.fit_transform(X_train), columns=X.columns)
minmax_X_test = pd.DataFrame(min_max_scaler.fit_transform(X_test), columns=X.columns)

max_abs_scaler = preprocessing.MaxAbsScaler()
maxabs_data = pd.DataFrame(max_abs_scaler.fit_transform(X), columns=X.columns)
maxabs_X_train = pd.DataFrame(max_abs_scaler.fit_transform(X_train), columns=X.columns)
maxabs_X_test = pd.DataFrame(max_abs_scaler.fit_transform(X_test), columns=X.columns)

robust_scaler = preprocessing.RobustScaler()
robust_data = pd.DataFrame(robust_scaler.fit_transform(X), columns=X.columns)
robust_X_train = pd.DataFrame(robust_scaler.fit_transform(X_train), columns=X.columns)
robust_X_test = pd.DataFrame(robust_scaler.fit_transform(X_test), columns=X.columns)

scaled_data = {
    'Standardized' : 
    {
        'data': standard_data,
        'train':standardized_X_train,
        'test':standardized_X_test
    },
    'Min_Max': 
    {
        'data':minmax_data,
        'train':minmax_X_train,
        'test':minmax_X_test
    },
    'Absolute_max': 
    {
        'data':maxabs_data,
        'train':maxabs_X_train,
        'test':maxabs_X_test
    },
    'Robust':
    {
        'data':robust_data,
        'train':robust_X_train,
        'test':robust_X_test
    },
}

In [29]:
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from sklearn.feature_selection import f_classif

In [30]:
feature_selection = []
for name in scaled_data :
    if name!='Standardized' and name!='Robust':
        d1 = {}
        d1['Processing'] = name
        d1['Method'] = "Univariate Selection"
        chi_selector = SelectKBest(chi2, k='all')
        fit = chi_selector.fit(scaled_data[name]['data'], y)
        d1['Features'] = dict(sorted(zip(scaled_data[name]['data'].columns, fit.scores_), key = lambda x: x[1],reverse=True))
        feature_selection.append(d1)
    
    ###############################

    d2 = {}
    d2['Processing'] = name
    d2['Method'] = "Extra Tree Classifier"
    etc = ExtraTreesClassifier()
    etc.fit(scaled_data[name]['data'],y)
    d2['Features'] = dict(sorted(zip(scaled_data[name]['data'].columns, etc.feature_importances_), key = lambda x: x[1],reverse=True))
    feature_selection.append(d2)

    ###############################

    d3 = {}
    d3['Processing'] = name
    d3['Method'] = "Random Forest Classifier"
    rf = RandomForestClassifier(n_estimators=500, random_state=7)
    rf.fit(scaled_data[name]['data'], y)
    d3['Features'] = dict(sorted(zip(scaled_data[name]['data'].columns, rf.feature_importances_), key = lambda x: x[1],reverse=True))
    feature_selection.append(d3)

    ###############################

    d4 = {}
    d4['Processing'] = name
    d4['Method'] = "LGBM Classifier"
    lgbc=LGBMClassifier(n_estimators=500, learning_rate=0.0001,
                    num_leaves=32, colsample_bytree=0.2,                                           
                    reg_alpha=3, reg_lambda=1, min_split_gain=0.01,    
                    min_child_weight=40)
    lgbc.fit(scaled_data[name]['data'], y)
    d4['Features'] = dict(sorted(zip(scaled_data[name]['data'].columns, lgbc.feature_importances_), key = lambda x: x[1],reverse=True))
    feature_selection.append(d4)

    ###############################

    d5 = {}
    d5['Processing'] = name
    d5['Method'] = "Correlation Matrix"
    t = pd.concat([scaled_data[name]['data'], y], axis=1)
    corrmat = t.corr()
    d5['Features'] = dict(sorted(zip(corrmat.iloc[:-1,:]['Target'].index,abs(corrmat.iloc[:-1,:]['Target'].values)),key = lambda x: x[1],reverse=True)) 
    feature_selection.append(d5) 

    ###############################

    d6 = {}
    d6['Processing'] = name
    d6['Method'] = "ANOVA F-SCORES"
    anov_selector = SelectKBest(f_classif, k='all')
    fit = anov_selector.fit(scaled_data[name]['data'], y)
    d6['Features'] = dict(sorted(zip(scaled_data[name]['data'].columns, fit.scores_), key = lambda x: x[1], reverse=True))
    feature_selection.append(d6)

In [31]:
feature_selection

[{'Processing': 'Standardized',
  'Method': 'Extra Tree Classifier',
  'Features': {'TB': 0.13440824650561234,
   'SGPT': 0.130967632313668,
   'AP': 0.11223357519078869,
   'Age': 0.11049206656214512,
   'SGOT': 0.1077786659674943,
   'DB': 0.10205250811529824,
   'A/G': 0.09412208690115077,
   'ALB': 0.09219431677822248,
   'TP': 0.08604417576938753,
   'Gender': 0.029706725896232425}},
 {'Processing': 'Standardized',
  'Method': 'Random Forest Classifier',
  'Features': {'SGOT': 0.13817372904692074,
   'AP': 0.1351446300274118,
   'SGPT': 0.13230301894183633,
   'TB': 0.12984289099957616,
   'Age': 0.11581395821364272,
   'DB': 0.08972985362892902,
   'ALB': 0.08297086390852793,
   'TP': 0.08241202526544614,
   'A/G': 0.0746668314276956,
   'Gender': 0.018942198540013507}},
 {'Processing': 'Standardized',
  'Method': 'LGBM Classifier',
  'Features': {'SGOT': 238,
   'ALB': 178,
   'Age': 177,
   'TB': 151,
   'AP': 145,
   'DB': 81,
   'SGPT': 59,
   'A/G': 55,
   'TP': 26,
   'Gender': 12}},
 {'Processing': 'Standardized',
  'Method': 'Correlation Matrix',
  'Features': {'TB': 0.3837873993919252,
   'SGPT': 0.3629673627291409,
   'DB': 0.3192431131606177,
   'AP': 0.2834200096397236,
   'A/G': 0.23380951412315037,
   'ALB': 0.2084264777000385,
   'SGOT': 0.20117192632627964,
   'Age': 0.17292414179778698,
   'Gender': 0.10068968497714356,
   'TP': 0.060829071688915715}},
 {'Processing': 'Standardized',
  'Method': 'ANOVA F-SCORES',
  'Features': {'TB': 143.3704239696507,
   'SGPT': 125.94070049293143,
   'DB': 94.1898895526871,
   'AP': 72.49459474503863,
   'A/G': 47.99738552411122,
   'ALB': 37.69401330376952,
   'SGOT': 35.00695602084448,
   'Age': 25.584331924722306,
   'Gender': 8.50106986278827,
   'TP': 3.0825520338431187}},
 {'Processing': 'Min_Max',
  'Method': 'Univariate Selection',
  'Features': {'DB': 24.058101683924253,
   'TB': 21.995222159413697,
   'SGPT': 11.323174634492062,
   'SGOT': 5.223568519985783,
   'AP': 3.5520314985556767,
   'A/G': 2.3425282129085185,
   'Gender': 2.2405891980360066,
   'Age': 2.1468086532332595,
   'ALB': 2.0794732960371274,
   'TP': 0.13380631326174697}},
 {'Processing': 'Min_Max',
  'Method': 'Extra Tree Classifier',
  'Features': {'TB': 0.13947823131028048,
   'SGPT': 0.1355519412609175,
   'AP': 0.11539297615646092,
   'Age': 0.10991101387952877,
   'SGOT': 0.10433507293725337,
   'DB': 0.10289933382776052,
   'ALB': 0.08992198014775347,
   'A/G': 0.0895288007599972,
   'TP': 0.08215263237411322,
   'Gender': 0.030828017345934645}},
 {'Processing': 'Min_Max',
  'Method': 'Random Forest Classifier',
  'Features': {'SGOT': 0.13817372904692074,
   'AP': 0.1351446300274118,
   'SGPT': 0.13230301894183633,
   'TB': 0.12984289099957616,
   'Age': 0.11581395821364272,
   'DB': 0.08972985362892902,
   'ALB': 0.08297086390852793,
   'TP': 0.08241202526544614,
   'A/G': 0.0746668314276956,
   'Gender': 0.018942198540013507}},
 {'Processing': 'Min_Max',
  'Method': 'LGBM Classifier',
  'Features': {'SGOT': 238,
   'ALB': 178,
   'Age': 177,
   'TB': 151,
   'AP': 145,
   'DB': 81,
   'SGPT': 59,
   'A/G': 55,
   'TP': 26,
   'Gender': 12}},
 {'Processing': 'Min_Max',
  'Method': 'Correlation Matrix',
  'Features': {'TB': 0.3837873993919249,
   'SGPT': 0.3629673627291415,
   'DB': 0.31924311316061804,
   'AP': 0.2834200096397243,
   'A/G': 0.23380951412314907,
   'ALB': 0.20842647770003941,
   'SGOT': 0.2011719263262796,
   'Age': 0.17292414179778678,
   'Gender': 0.10068968497714316,
   'TP': 0.060829071688918115}},
 {'Processing': 'Min_Max',
  'Method': 'ANOVA F-SCORES',
  'Features': {'TB': 143.37042396965052,
   'SGPT': 125.94070049293188,
   'DB': 94.18988955268695,
   'AP': 72.4945947450371,
   'A/G': 47.99738552411274,
   'ALB': 37.69401330377046,
   'SGOT': 35.00695602084438,
   'Age': 25.584331924723408,
   'Gender': 8.501069862788158,
   'TP': 3.08255203384498}},
 {'Processing': 'Absolute_max',
  'Method': 'Univariate Selection',
  'Features': {'DB': 21.857413970225537,
   'TB': 13.035640462828644,
   'SGOT': 4.62374258101604,
   'SGPT': 2.6525714146619537,
   'Gender': 2.2405891980360066,
   'Age': 1.8614699827519074,
   'ALB': 1.2536941138193711,
   'A/G': 1.1467067186221747,
   'AP': 0.38144034709651,
   'TP': 0.05637304569961652}},
 {'Processing': 'Absolute_max',
  'Method': 'Extra Tree Classifier',
  'Features': {'SGPT': 0.1339707133253665,
   'TB': 0.12467552186296516,
   'AP': 0.12260850196087868,
   'Age': 0.11239476132722657,
   'SGOT': 0.10720638702364862,
   'DB': 0.10669844546350263,
   'A/G': 0.09049026080270069,
   'ALB': 0.08918369260668138,
   'TP': 0.08387881279502166,
   'Gender': 0.0288929028320082}},
 {'Processing': 'Absolute_max',
  'Method': 'Random Forest Classifier',
  'Features': {'SGOT': 0.13817372904692074,
   'AP': 0.1351446300274118,
   'SGPT': 0.13230301894183633,
   'TB': 0.12984289099957616,
   'Age': 0.11581395821364272,
   'DB': 0.08972985362892902,
   'ALB': 0.08297086390852793,
   'TP': 0.08241202526544614,
   'A/G': 0.0746668314276956,
   'Gender': 0.018942198540013507}},
 {'Processing': 'Absolute_max',
  'Method': 'LGBM Classifier',
  'Features': {'SGOT': 238,
   'ALB': 178,
   'Age': 177,
   'TB': 151,
   'AP': 145,
   'DB': 81,
   'SGPT': 59,
   'A/G': 55,
   'TP': 26,
   'Gender': 12}},
 {'Processing': 'Absolute_max',
  'Method': 'Correlation Matrix',
  'Features': {'TB': 0.3837873993919253,
   'SGPT': 0.36296736272913976,
   'DB': 0.31924311316061804,
   'AP': 0.2834200096397168,
   'A/G': 0.2338095141231465,
   'ALB': 0.20842647770004027,
   'SGOT': 0.20117192632627962,
   'Age': 0.17292414179778673,
   'Gender': 0.10068968497714316,
   'TP': 0.06082907168891622}},
 {'Processing': 'Absolute_max',
  'Method': 'ANOVA F-SCORES',
  'Features': {'TB': 143.37042396964966,
   'SGPT': 125.94070049292313,
   'DB': 94.18988955268732,
   'AP': 72.49459474500618,
   'A/G': 47.997385524111905,
   'ALB': 37.694013303767015,
   'SGOT': 35.00695602084432,
   'Age': 25.584331924721276,
   'Gender': 8.501069862788158,
   'TP': 3.0825520338436716}},
 {'Processing': 'Robust',
  'Method': 'Extra Tree Classifier',
  'Features': {'SGPT': 0.13743311601603023,
   'TB': 0.12827293526152386,
   'AP': 0.1188023478058922,
   'Age': 0.10991646632944647,
   'SGOT': 0.10818477405291739,
   'DB': 0.10528233103432118,
   'ALB': 0.09182684260083832,
   'A/G': 0.09005799628055343,
   'TP': 0.07985855110296673,
   'Gender': 0.03036463951551035}},
 {'Processing': 'Robust',
  'Method': 'Random Forest Classifier',
  'Features': {'SGOT': 0.13817372904692074,
   'AP': 0.1351446300274118,
   'SGPT': 0.13230301894183633,
   'TB': 0.12984289099957616,
   'Age': 0.11581395821364272,
   'DB': 0.08972985362892902,
   'ALB': 0.08297086390852793,
   'TP': 0.08241202526544614,
   'A/G': 0.0746668314276956,
   'Gender': 0.018942198540013507}},
 {'Processing': 'Robust',
  'Method': 'LGBM Classifier',
  'Features': {'SGOT': 238,
   'ALB': 178,
   'Age': 177,
   'TB': 151,
   'AP': 145,
   'DB': 81,
   'SGPT': 59,
   'A/G': 55,
   'TP': 26,
   'Gender': 12}},
 {'Processing': 'Robust',
  'Method': 'Correlation Matrix',
  'Features': {'TB': 0.3837873993919246,
   'SGPT': 0.36296736272914154,
   'DB': 0.3192431131606178,
   'AP': 0.2834200096397241,
   'A/G': 0.23380951412315032,
   'ALB': 0.20842647770003842,
   'SGOT': 0.20117192632627962,
   'Age': 0.17292414179778703,
   'Gender': 0.1006896849771432,
   'TP': 0.060829071688915395}},
 {'Processing': 'Robust',
  'Method': 'ANOVA F-SCORES',
  'Features': {'TB': 143.3704239696515,
   'SGPT': 125.94070049293198,
   'DB': 94.18988955268712,
   'AP': 72.49459474503888,
   'A/G': 47.99738552411112,
   'ALB': 37.69401330376937,
   'SGOT': 35.006956020844406,
   'Age': 25.584331924722253,
   'Gender': 8.501069862788233,
   'TP': 3.082552033843124}}]

# Model Selection

## Gradient Boosting

## Bagging

## Stacking

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from chefboost import Chefboost as chef
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.ensemble import GradientBoostingClassifier

In [60]:
results = []
best_result = {}
cross_best_result = {}
max_accuracy = 0
max_cross_acc = 0
for method in feature_selection:
    data = scaled_data[method['Processing']]
    for i in range(3,11):
        info = {}
        info['Processing'] = method['Processing']
        info['Method'] = method['Method']
        info['Features'] = list(method['Features'].keys())[:i]
        
        data = scaled_data[method['Processing']]['data'][info['Features']]
        X_train = scaled_data[method['Processing']]['train'][info['Features']]
        X_test = scaled_data[method['Processing']]['test'][info['Features']]
        
        model = RandomForestClassifier(n_jobs=-1,random_state=123)
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        predictions = [round(value) for value in y_pred]
        accuracy = accuracy_score(y_test, predictions)*100

        # K-Fold Cross Validation
        kfold = StratifiedKFold(n_splits=10)
        crossval_results = cross_val_score(model, data, y, cv=kfold)
        cross_acc = crossval_results.mean()*100
        info['Cross Validation Accuracy'] = cross_acc
        info['Accuracy'] = accuracy
        if accuracy>max_accuracy:
            max_accuracy = accuracy
            best_result = info
        if cross_acc>max_cross_acc:
            max_cross_acc = cross_acc
            cross_best_result = info

In [61]:
best_result

{'Processing': 'Robust',
 'Method': 'Extra Tree Classifier',
 'Features': ['SGPT', 'TB', 'AP', 'Age', 'SGOT'],
 'Cross Validation Accuracy': 87.7409638554217,
 'Accuracy': 81.73076923076923}

In [62]:
cross_best_result

{'Processing': 'Standardized',
 'Method': 'Random Forest Classifier',
 'Features': ['SGOT', 'AP', 'SGPT', 'TB'],
 'Cross Validation Accuracy': 88.58433734939759,
 'Accuracy': 63.46153846153846}

In [39]:
from sklearn.model_selection import GridSearchCV, KFold

In [63]:
params = {
    'n_estimators': [100, 150, 200, 500],
    'criterion': ['gini', 'entropy'],
    'min_samples_split': [1,2,4,5,None],
    'min_samples_leaf': [1,2,4,5,None],
    'max_leaf_nodes': [None]
}

gs1 = GridSearchCV(RandomForestClassifier(n_jobs=-1), params, n_jobs=-1, cv=KFold(n_splits=10), scoring='accuracy')
gs1.fit(X_train[['SGPT', 'TB', 'AP', 'Age', 'SGOT']], y_train)

print('Best score:', gs1.best_score_)
print('Best score:', gs1.best_params_)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
1040 fits failed out of a total of 2000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
320 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 450, in fit
    trees = Parallel(
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\LENOVO\anaconda3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\LENOVO\anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 216, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 185, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 937, in fit
    super().fit(
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 250, in fit
    raise ValueError(
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

--------------------------------------------------------------------------------
320 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 450, in fit
    trees = Parallel(
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\LENOVO\anaconda3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\LENOVO\anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 216, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 185, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 937, in fit
    super().fit(
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 258, in fit
    if not 0.0 < self.min_samples_split <= 1.0:
TypeError: '<' not supported between instances of 'float' and 'NoneType'

--------------------------------------------------------------------------------
400 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 450, in fit
    trees = Parallel(
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\LENOVO\anaconda3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\LENOVO\anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 216, in __call__
    return self.function(*args, **kwargs)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 185, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 937, in fit
    super().fit(
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 241, in fit
    if not 0.0 < self.min_samples_leaf <= 0.5:
TypeError: '<' not supported between instances of 'float' and 'NoneType'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan 0.85074245 0.84275474
 0.84907834 0.84434204 0.84918075 0.85084485 0.84754224 0.84915515
 0.84111623 0.84114183 0.83635433 0.84116743        nan        nan
        nan        nan        nan        nan        nan        nan
 0.83479263 0.83791603 0.83799283 0.83630312 0.84119304 0.83469022
 0.83476703 0.83952893 0.83320533 0.83154122 0.83950333 0.82990271
        nan        nan        nan        nan        nan        nan
        nan        nan 0.81554019 0.8108807  0.81082949 0.80768049
 0.80604199 0.80442908 0.81075269 0.80921659 0.80911418 0.81239119
 0.81080389 0.80762929        nan        nan        nan        nan
        nan        nan        nan        nan 0.79953917 0.79797747
 0.79966718 0.80286738 0.79641577 0.79331797 0.80448029 0.80606759
 0.79004096 0.79321557 0.79964158 0.79482847        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.84434204 0.84431644 0.85076805 0.85071685
 0.84124424 0.84600614 0.84759345 0.84598054 0.84275474 0.84434204
 0.84598054 0.84121864        nan        nan        nan        nan
        nan        nan        nan        nan 0.83310292 0.83476703
 0.83799283 0.83637993 0.83637993 0.83958013 0.84434204 0.83952893
 0.82352791 0.83635433 0.83637993 0.83471582        nan        nan
        nan        nan        nan        nan        nan        nan
 0.81236559 0.8156426  0.81241679 0.8203533  0.8140297  0.8155914
 0.81080389 0.82040451 0.80770609 0.8140297  0.8203789  0.8203789
        nan        nan        nan        nan        nan        nan
        nan        nan 0.80760369 0.79477727 0.80437788 0.80606759
 0.79800307 0.80442908 0.79959037 0.80762929 0.80757808 0.80440348
 0.80122888 0.80442908        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan]
  warnings.warn(

Best score: 0.8508448540706606
Best score: {'criterion': 'gini', 'max_leaf_nodes': None, 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 150}

In [65]:
accuracy_score(y_test, gs1.predict(X_test[['SGPT', 'TB', 'AP', 'Age', 'SGOT']]))

0.7932692307692307

In [59]:
X_train = scaled_data['Robust']['train']
X_test = scaled_data['Robust']['test']
data = scaled_data['Robust']['data']
model = RandomForestClassifier(n_jobs=-1,random_state=123)
model.fit(X_train[['SGPT', 'TB', 'AP', 'Age', 'SGOT']], y_train)
y_pred = model.predict(X_test[['SGPT', 'TB', 'AP', 'Age', 'SGOT']])
predictions = [round(value) for value in y_pred]
accuracy = accuracy_score(y_test, predictions)*100

kfold = StratifiedKFold(n_splits=10)
crossval_results = cross_val_score(model, data[['SGPT', 'TB', 'AP', 'Age', 'SGOT']], y, cv=kfold)
cross_acc = crossval_results.mean()*100
print(accuracy,cross_acc)

70.67307692307693 86.78141135972461

In [66]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

print(model)
print('Train performance')
print('-------------------------------------------------------')
print(classification_report(y_train, model.predict(X_train)))

print('Test performance')
print('-------------------------------------------------------')
print(classification_report(y_test, y_pred))

print('Roc_auc score')
print('-------------------------------------------------------')
print(roc_auc_score(y_test, y_pred))
print('')

print('Confusion matrix')
print('-------------------------------------------------------')
print(confusion_matrix(y_test, y_pred))

RandomForestClassifier(n_jobs=-1, random_state=123)
Train performance
-------------------------------------------------------
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00       313
         2.0       1.00      1.00      1.00       311

    accuracy                           1.00       624
   macro avg       1.00      1.00      1.00       624
weighted avg       1.00      1.00      1.00       624

Test performance
-------------------------------------------------------
              precision    recall  f1-score   support

         1.0       0.78      0.75      0.76       103
         2.0       0.76      0.79      0.78       105

    accuracy                           0.77       208
   macro avg       0.77      0.77      0.77       208
weighted avg       0.77      0.77      0.77       208

Roc_auc score
-------------------------------------------------------
0.7690245030050855

Confusion matrix
-------------------------------------------------------
[[77 26]
 [22 83]]